include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(APRG_EQUATION_SOURCE_DIRECTORY
    ${APRG_EQUATION_DIR}/src
)

set(APRG_EQUATION_TEST_DIRECTORY
    ${APRG_EQUATION_DIR}/tst
)

set(APRG_EQUATION_MAIN_DIRECTORY
    ${APRG_EQUATION_DIR}/main
)

set(APRG_EQUATION_INCLUDE_DIRECTORIES
    ${APRG_EQUATION_SOURCE_DIRECTORY}
)

set(APRG_EQUATION_TEST_INCLUDE_DIRECTORIES
    ${APRG_EQUATION_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_EQUATION_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_EQUATION_SOURCE_DIRECTORY_LIST ${APRG_EQUATION_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_EQUATION_SOURCES APRG_EQUATION_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_EQUATION_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_EQUATION_TEST_DIRECTORY_LIST ${APRG_EQUATION_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_EQUATION_TESTS APRG_EQUATION_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${APRG_EQUATION_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_EQUATION_MAIN_DIRECTORY_LIST ${APRG_EQUATION_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_EQUATION_MAIN_SOURCES APRG_EQUATION_MAIN_DIRECTORY_LIST)

set(APRG_EQUATION_SOURCES_AND_TESTS
    ${APRG_EQUATION_SOURCES}
    ${APRG_EQUATION_TESTS}
)
