include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(CHESS_ENGINE_HANDLER_SOURCE_DIRECTORY
    ${CHESS_ENGINE_HANDLER_DIR}/src
)

set(CHESS_ENGINE_HANDLER_TEST_DIRECTORY
    ${CHESS_ENGINE_HANDLER_DIR}/tst
)

set(CHESS_ENGINE_HANDLER_MAIN_DIRECTORY
    ${CHESS_ENGINE_HANDLER_DIR}/main
)

set(CHESS_ENGINE_HANDLER_INCLUDE_DIRECTORIES
    ${CHESS_ENGINE_HANDLER_SOURCE_DIRECTORY}
)

set(CHESS_ENGINE_HANDLER_TEST_INCLUDE_DIRECTORIES
    ${CHESS_ENGINE_HANDLER_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${CHESS_ENGINE_HANDLER_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(CHESS_ENGINE_HANDLER_SOURCE_DIRECTORY_LIST ${CHESS_ENGINE_HANDLER_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(CHESS_ENGINE_HANDLER_SOURCES CHESS_ENGINE_HANDLER_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${CHESS_ENGINE_HANDLER_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(CHESS_ENGINE_HANDLER_TEST_DIRECTORY_LIST ${CHESS_ENGINE_HANDLER_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(CHESS_ENGINE_HANDLER_TESTS CHESS_ENGINE_HANDLER_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${CHESS_ENGINE_HANDLER_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(CHESS_ENGINE_HANDLER_MAIN_DIRECTORY_LIST ${CHESS_ENGINE_HANDLER_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(CHESS_ENGINE_HANDLER_MAIN_SOURCES CHESS_ENGINE_HANDLER_MAIN_DIRECTORY_LIST)

set(CHESS_ENGINE_HANDLER_SOURCES_AND_TESTS
    ${CHESS_ENGINE_HANDLER_SOURCES}
    ${CHESS_ENGINE_HANDLER_TESTS}
)
