include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(STRING_REPLACER_SOURCE_DIRECTORY
    ${STRING_REPLACER_DIR}/src
)

set(STRING_REPLACER_TEST_DIRECTORY
    ${STRING_REPLACER_DIR}/tst
)

set(STRING_REPLACER_INCLUDE_DIRECTORIES
    ${STRING_REPLACER_SOURCE_DIRECTORY}
)

set(STRING_REPLACER_TEST_INCLUDE_DIRECTORIES
    ${STRING_REPLACER_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${STRING_REPLACER_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(STRING_REPLACER_SOURCE_DIRECTORY_LIST ${STRING_REPLACER_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(STRING_REPLACER_SOURCES STRING_REPLACER_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${STRING_REPLACER_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(STRING_REPLACER_TEST_DIRECTORY_LIST ${STRING_REPLACER_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(STRING_REPLACER_TESTS STRING_REPLACER_TEST_DIRECTORY_LIST)

set(STRING_REPLACER_SOURCES_AND_TESTS
    ${STRING_REPLACER_SOURCES}
    ${STRING_REPLACER_TESTS}
)
