include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(BOOST_SOURCE_DIRECTORY
    ${BOOST_DIR}/src
)

set(BOOST_TEST_DIRECTORY
    ${BOOST_DIR}/tst
)

set(BOOST_INCLUDE_DIRECTORIES
    ${BOOST_SOURCE_DIRECTORY}
)

set(BOOST_TEST_INCLUDE_DIRECTORIES
    ${BOOST_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${BOOST_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(BOOST_SOURCE_DIRECTORY_LIST ${BOOST_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(BOOST_SOURCES BOOST_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${BOOST_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(BOOST_TEST_DIRECTORY_LIST ${BOOST_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(BOOST_TESTS BOOST_TEST_DIRECTORY_LIST)

set(BOOST_SOURCES_AND_TESTS
    ${BOOST_SOURCES}
    ${BOOST_TESTS}
)
