#Common macros

macro(MACRO_GET_ALL_SOURCES currentDirectory result)
    unset(${result})
    #message(STATUS "MACRO_GET_ALL_SOURCES currentDirectory: ${currentDirectory}")
    MACRO_GET_ALL_SUBDIRECTORIES(${currentDirectory} subDirectories)
    MACRO_GET_SOURCES_FROM_LIST("${subDirectories}" ${result})
    #message(STATUS "MACRO_GET_ALL_SOURCES result: ${${result}}")
endmacro()

macro(MACRO_GET_ALL_SUBDIRECTORIES currentDirectory result)
    unset(${result})
    MACRO_GET_ALL_SUBDIRECTORIES_RECUSIVE(${currentDirectory} ${result})
    #message(STATUS "MACRO_GET_ALL_SUBDIRECTORIES result: ${${result}}")
endmacro()

macro(MACRO_GET_ALL_SUBDIRECTORIES_RECUSIVE currentDirectory result)
    #message(STATUS "MACRO_GET_ALL_SUBDIRECTORIES_RECUSIVE currentDirectory: ${currentDirectory}")
    file(GLOB fileOrDirectoryList RELATIVE ${currentDirectory} ${currentDirectory}/*)
    foreach(fileOrDirectory ${fileOrDirectoryList})
      set(newDirectory ${currentDirectory}/${fileOrDirectory})
      if(IS_DIRECTORY ${newDirectory})
        list(APPEND ${result} ${newDirectory})
        MACRO_GET_ALL_SUBDIRECTORIES_RECUSIVE(${newDirectory} ${result})
      endif()
    endforeach()
endmacro()

macro(MACRO_GET_SOURCES_FROM_LIST subDirectories result)
    unset(${result})
    #message(STATUS "MACRO_GET_SOURCES_FROM_LIST subDirectories: ${subDirectories}")
    foreach(subDirectory ${subDirectories})
        MACRO_GET_SOURCES_IN_ONE_DIRECTORY(subDirectory ${result})
    endforeach()
endmacro()

macro(MACRO_GET_SOURCES_IN_ONE_DIRECTORY directory result)
    #message(STATUS "MACRO_GET_SOURCES_IN_ONE_DIRECTORY directory: ${${directory}}")
    file(GLOB files ${${directory}}/*.cpp ${${directory}}/*.hpp ${${directory}}/*.c ${${directory}}/*.h)
    foreach(filename ${files})
        #message(STATUS "MACRO_GET_SOURCES_IN_ONE_DIRECTORY Adding file: ${filename}")
        list(APPEND ${result} ${filename})
    endforeach()
    #message(STATUS "MACRO_GET_SOURCES_IN_ONE_DIRECTORY result: ${${result}}")
endmacro()

macro(PRINT_ELEMENTS elements)
    foreach(element ${${elements}})
        #message(STATUS "Element: ${element}")
    endforeach()
endmacro()