include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(DISPLAY_TABLE_SOURCE_DIRECTORY
    ${DISPLAY_TABLE_DIR}/src
)

set(DISPLAY_TABLE_TEST_DIRECTORY
    ${DISPLAY_TABLE_DIR}/tst
)

set(DISPLAY_TABLE_INCLUDE_DIRECTORIES
    ${DISPLAY_TABLE_SOURCE_DIRECTORY}
)

set(DISPLAY_TABLE_TEST_INCLUDE_DIRECTORIES
    ${DISPLAY_TABLE_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${DISPLAY_TABLE_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(DISPLAY_TABLE_SOURCE_DIRECTORY_LIST ${DISPLAY_TABLE_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(DISPLAY_TABLE_SOURCES DISPLAY_TABLE_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${DISPLAY_TABLE_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(DISPLAY_TABLE_TEST_DIRECTORY_LIST ${DISPLAY_TABLE_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(DISPLAY_TABLE_TESTS DISPLAY_TABLE_TEST_DIRECTORY_LIST)

set(DISPLAY_TABLE_SOURCES_AND_TESTS
    ${DISPLAY_TABLE_SOURCES}
    ${DISPLAY_TABLE_TESTS}
)
