set(APRG_FILE_EXTRACTOR_INCLUDE_DIRECTORIES
    ${APRG_FILE_EXTRACTOR_DIR}/src
)

set(APRG_FILE_EXTRACTOR_TEST_INCLUDE_DIRECTORIES
    ${APRG_FILE_EXTRACTOR_DIR}/tst
)

set(APRG_FILE_EXTRACTOR_SOURCES
    ${APRG_FILE_EXTRACTOR_DIR}/src/AprgFileExtractor.cpp
    ${APRG_FILE_EXTRACTOR_DIR}/src/AprgFileExtractor.hpp
)

set(APRG_FILE_EXTRACTOR_TESTS
    ${APRG_FILE_EXTRACTOR_DIR}/tst/AprgFileExtractor_unit.cpp
)

set(APRG_FILE_EXTRACTOR_SOURCES_AND_TESTS
    ${APRG_FILE_EXTRACTOR_SOURCES}
    ${APRG_FILE_EXTRACTOR_TESTS}
)
