set(APRG_GEOMETRY_INCLUDE_DIRECTORIES
    ${APRG_GEOMETRY_DIR}/src
)

set(APRG_GEOMETRY_TEST_INCLUDE_DIRECTORIES
    ${APRG_GEOMETRY_DIR}/tst
)

set(APRG_GEOMETRY_SOURCES
    ${APRG_GEOMETRY_DIR}/src/TwoDimensions/Line.cpp
    ${APRG_GEOMETRY_DIR}/src/TwoDimensions/Line.hpp
)

set(APRG_GEOMETRY_TESTS
    ${APRG_GEOMETRY_DIR}/tst/TwoDimensions/Line_unit.cpp
)

set(APRG_GEOMETRY_SOURCES_AND_TESTS
    ${APRG_GEOMETRY_SOURCES}
    ${APRG_GEOMETRY_TESTS}
)
