include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(APRG_MATH_SET_SOURCE_DIRECTORY
    ${APRG_MATH_SET_DIR}/src
)

set(APRG_MATH_SET_TEST_DIRECTORY
    ${APRG_MATH_SET_DIR}/tst
)

set(APRG_MATH_SET_INCLUDE_DIRECTORIES
    ${APRG_MATH_SET_SOURCE_DIRECTORY}
)

set(APRG_MATH_SET_TEST_INCLUDE_DIRECTORIES
    ${APRG_MATH_SET_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${APRG_MATH_SET_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_MATH_SET_SOURCE_DIRECTORY_LIST ${APRG_MATH_SET_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_MATH_SET_SOURCES APRG_MATH_SET_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${APRG_MATH_SET_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(APRG_MATH_SET_TEST_DIRECTORY_LIST ${APRG_MATH_SET_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(APRG_MATH_SET_TESTS APRG_MATH_SET_TEST_DIRECTORY_LIST)

set(APRG_MATH_SET_SOURCES_AND_TESTS
    ${APRG_MATH_SET_SOURCES}
    ${APRG_MATH_SET_TESTS}
)
