set(APRG_BITMAP_FILTERS_INCLUDE_DIRECTORIES
    ${APRG_BITMAP_FILTERS_DIR}/src
)

set(APRG_BITMAP_FILTERS_TEST_INCLUDE_DIRECTORIES
    ${APRG_BITMAP_FILTERS_DIR}/tst
)

set(APRG_BITMAP_FILTERS_SOURCES
    ${APRG_BITMAP_FILTERS_DIR}/src/AprgBitmapFilters.cpp
    ${APRG_BITMAP_FILTERS_DIR}/src/AprgBitmapFilters.hpp
    ${APRG_BITMAP_FILTERS_DIR}/src/PixelInformationDatabase.cpp
    ${APRG_BITMAP_FILTERS_DIR}/src/PixelInformationDatabase.hpp
)

set(APRG_BITMAP_FILTERS_TESTS
    ${APRG_BITMAP_FILTERS_DIR}/tst/AprgBitmapFilters_unit.cpp
)

set(APRG_BITMAP_FILTERS_SOURCES_AND_TESTS
    ${APRG_BITMAP_FILTERS_SOURCES}
    ${APRG_BITMAP_FILTERS_TESTS}
)
