include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(TCOM_TOOLS_BACKEND_SOURCE_DIRECTORY
    ${TCOM_TOOLS_BACKEND_DIR}/src
)

set(TCOM_TOOLS_BACKEND_TEST_DIRECTORY
    ${TCOM_TOOLS_BACKEND_DIR}/tst
)

set(TCOM_TOOLS_BACKEND_INCLUDE_DIRECTORIES
    ${TCOM_TOOLS_BACKEND_SOURCE_DIRECTORY}
)

set(TCOM_TOOLS_BACKEND_TEST_INCLUDE_DIRECTORIES
    ${TCOM_TOOLS_BACKEND_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${TCOM_TOOLS_BACKEND_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(TCOM_TOOLS_BACKEND_SOURCE_DIRECTORY_LIST ${TCOM_TOOLS_BACKEND_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(TCOM_TOOLS_BACKEND_SOURCES TCOM_TOOLS_BACKEND_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${TCOM_TOOLS_BACKEND_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(TCOM_TOOLS_BACKEND_TEST_DIRECTORY_LIST ${TCOM_TOOLS_BACKEND_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(TCOM_TOOLS_BACKEND_TESTS TCOM_TOOLS_BACKEND_TEST_DIRECTORY_LIST)

set(TCOM_TOOLS_BACKEND_SOURCES_AND_TESTS
    ${TCOM_TOOLS_BACKEND_SOURCES}
    ${TCOM_TOOLS_BACKEND_TESTS}
)
