include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(GNUPLOT_IOSTREAM_SOURCE_DIRECTORY
    ${GNUPLOT_IOSTREAM_DIR}/src
)

set(GNUPLOT_IOSTREAM_TEST_DIRECTORY
    ${GNUPLOT_IOSTREAM_DIR}/tst
)

set(GNUPLOT_IOSTREAM_INCLUDE_DIRECTORIES
    ${GNUPLOT_IOSTREAM_SOURCE_DIRECTORY}
)

set(GNUPLOT_IOSTREAM_TEST_INCLUDE_DIRECTORIES
    ${GNUPLOT_IOSTREAM_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${GNUPLOT_IOSTREAM_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(GNUPLOT_IOSTREAM_SOURCE_DIRECTORY_LIST ${GNUPLOT_IOSTREAM_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(GNUPLOT_IOSTREAM_SOURCES GNUPLOT_IOSTREAM_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${GNUPLOT_IOSTREAM_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(GNUPLOT_IOSTREAM_TEST_DIRECTORY_LIST ${GNUPLOT_IOSTREAM_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(GNUPLOT_IOSTREAM_TESTS GNUPLOT_IOSTREAM_TEST_DIRECTORY_LIST)

set(GNUPLOT_IOSTREAM_SOURCES_AND_TESTS
    ${GNUPLOT_IOSTREAM_SOURCES}
    ${GNUPLOT_IOSTREAM_TESTS}
)
