include(${APRG_DIR}/AprgCMakeHelpers/FileAndDirectoryMacros.cmake)
include(${APRG_DIR}/AprgCMakeHelpers/PrintMacros.cmake)

set(CUBE_36_SOURCE_DIRECTORY
    ${CUBE_36_DIR}/src
)

set(CUBE_36_TEST_DIRECTORY
    ${CUBE_36_DIR}/tst
)

set(CUBE_36_MAIN_DIRECTORY
    ${CUBE_36_DIR}/main
)

set(CUBE_36_INCLUDE_DIRECTORIES
    ${CUBE_36_SOURCE_DIRECTORY}
)

set(CUBE_36_TEST_INCLUDE_DIRECTORIES
    ${CUBE_36_TEST_DIRECTORY}
)

PRINT_STATUS("Looking for SRC directories in: [${CUBE_36_SOURCE_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(CUBE_36_SOURCE_DIRECTORY_LIST ${CUBE_36_SOURCE_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(CUBE_36_SOURCES CUBE_36_SOURCE_DIRECTORY_LIST)

PRINT_STATUS("Looking for TST directories in: [${CUBE_36_TEST_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(CUBE_36_TEST_DIRECTORY_LIST ${CUBE_36_TEST_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(CUBE_36_TESTS CUBE_36_TEST_DIRECTORY_LIST)

PRINT_STATUS("Looking for MAIN directories in: [${CUBE_36_MAIN_DIRECTORY}]")
GET_SUB_DIRECTORY_LIST(CUBE_36_MAIN_DIRECTORY_LIST ${CUBE_36_MAIN_DIRECTORY})
GET_SOURCE_FILES_FROM_DIRECTORIES(CUBE_36_MAIN_SOURCES CUBE_36_MAIN_DIRECTORY_LIST)

set(CUBE_36_SOURCES_AND_TESTS
    ${CUBE_36_SOURCES}
    ${CUBE_36_TESTS}
)
