MACRO_GET_ALL_SOURCES(${DesignDocumentCreatorDirectory}/src/CNI21985 FEATURE_SOURCES)
MACRO_GET_ALL_SOURCES(${DesignDocumentCreatorDirectory}/tst/CNI21985 FEATURE_TESTS)
SET(FEATURE_INCLUDE_DIRECTORIES ${DesignDocumentCreatorDirectory}/src/CNI21985)

message(STATUS "FEATURE_SOURCES: ${FEATURE_SOURCES}")
message(STATUS "FEATURE_TESTS: ${FEATURE_TESTS}")

